#image: twalter/maven-docker
image: maven:3.6-jdk-11

#
#stages:
#  - build
#  - buildImages
#  - dockerCompose
#  - test
#
#build:
#  stage: build
#  script:
#    - mvn clean install -Dmaven.test.skip=true
#
#buildImages:
#  stage: buildImages
#  script:
#    - mvn spring-boot:build-image
#    - cd ..
#    - cd booking-system
#    - mvn spring-boot:build-image
#
#dockerCompose:
#  stage: dockerCompose
#  script:
#    - cd misc/docker
#    - docker-compose up -d
#
#test:
#  stage: test
#  script:
#    - cd api-test
#    - mvn clean verify
#  artifacts:
#    paths:
#      - target/site

test:
  script:
    - sudo apt-get update
    - sudo apt-get install \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg \
      lsb-release
    - docker --version
    - mvn clean install -Dmaven.test.skip=true
    - cd api
    - mvn spring-boot:build-image
    - cd ..
    - cd booking-system
    - mvn spring-boot:build-image
    - cd ..
    - cd misc/docker
    - docker-compose up -d
    - cd ../..
    - cd api-test
    - mvn clean verify
  artifacts:
    paths:
      - target/site
